language: erlang
notifications:
  email: false
otp_release:
  - 18.2
  - 18.1
  - 17.4
script: "cd example/buffer && make clean && make eunit && cd - && make clean && make eunit && make clean && make xref"
